version: '3'
services:
  mysql:
    build:
      context: mysql
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    logging:
      options:
        max-size: "10m"
        max-file: "3"